# -*- coding: utf-8 -*-
"""Car_Damage.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiUMAmKAwshDAuko60s4TnpPHV1esSWP
"""

!nvidia-smi

!git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet/
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile

!/usr/local/cuda/bin/nvcc --version

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

# Commented out IPython magic to ensure Python compatibility.
def imShow(path):
  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline

  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/

!cp /mydrive/AI/obj.zip ../

!unzip ../obj.zip -d darknet/data/

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet/

!cp /mydrive/AI/yolo_custom.cfg cfg/

!cp /mydrive/AI/obj.names data/
!cp /mydrive/AI/obj.data data/

!cp /mydrive/AI/script.py ./

!python script.py

!ls data/

# Commented out IPython magic to ensure Python compatibility.
# %cd ..

!wget http://pjreddie.com/media/files/darknet53.conv.74

# train your custom detector
!./darknet detector train data/obj.data cfg/yolo_custom.cfg darknet53.conv.74 -dont_show
# uncomment it and run to restart your model training from the last iteration it crashed

#!./darknet detector train data/obj.data cfg/yolo_custom.cfg /mydrive/AI/yolo_custom_last.weights -dont_show

# Commented out IPython magic to ensure Python compatibility.
# %cd cfg
!sed -i 's/batch=64/batch=1/' yolo_custom.cfg
!sed -i 's/subdivisions=16/subdivisions=1/' yolo_custom.cfg
# %cd ..

!./darknet detector test data/obj.data cfg/yolo_custom.cfg /mydrive/AI/yolo_custom_last.weights /mydrive/Images/fTm5x.jpg -Paint-Scratch-Remover.jpg -thresh 0.3

imShow('predictions.jpg')